### ISSUE TITLE
Add Control Point Type to OLAP telemetry

### ISSUE THREAD

**Issue by kwapik** [fluxninja/aperture#1093]
As Control Points, which are of HTTP type (may be Envoy, Java SDK Armeria decorator, etc.) carry much more information about the traffic, we'd like to have a way to distinguish OLAP telemetry coming from them.

To achieve this we need to populate one more OLAP telemetry attribute, which is `aperture.control_point_type`.

Implementation proposal:
- [ ] Add `string control_point` field, both to [`CheckRequest`](https://github.com/fluxninja/aperture/blob/main/api/aperture/flowcontrol/check/v1/check.proto#L14) and [`CheckResponse`](https://github.com/fluxninja/aperture/blob/main/api/aperture/flowcontrol/check/v1/check.proto#L20). It should be of type enum with values `FEATURE` and `HTTP` (order is important, as the enum value with 0 index would be the default).
- [ ] Set Control Point Type in the Check Response to equal the value from Check Request in [`Check` handler](https://github.com/fluxninja/aperture/blob/main/pkg/policies/flowcontrol/service/check/check.go#L61).
- [ ] Set Control Point Type in [Envoy Check Response](https://github.com/fluxninja/aperture/blob/main/pkg/policies/flowcontrol/service/envoy/authz.go#L182) to `HTTP`.
- [ ] Propagate the `aperture.control_point_type` in [`metricsprocessor`](https://github.com/fluxninja/aperture/blob/main/pkg/otelcollector/metricsprocessor/internal/check_response_labels.go#L32). Remember to add it to the [whitelist](https://github.com/fluxninja/aperture/blob/main/pkg/otelcollector/metricsprocessor/internal/labels_filter.go#L13).
- [ ] Update all [SDKs](https://github.com/fluxninja/aperture/tree/main/sdks) to send proper Control Point Type in check request.

**Comment by tanveergill** [comment]
@kwapik,

Can’t this be inferred on the server side since Features and HTTP based Flows are being received by different handlers as they have their own wire protocols. So, no need to set this explicitly in the payload. If another protocol such as MySQL needs to be supported it will be its own wire protocol as well. What do you think?

cc: @krdln, @harjotgill
