### ISSUE TITLE
Consistent units

### ISSUE THREAD

**Issue by tanveergill** [fluxninja/aperture#1149]
## What
* Concurrency metrics need to be renamed to reflect that they are measuring work done in units of time
* All metric units need to follow Prometheus base unit conventions
* Update Grafana dashboards in Blueprints to convey correct units. Panels plotting concurrency will become unit-less once rate query is applied on work done in seconds. Thus reflecting the concurrency of a service as absolute number.

**Comment by tanveergill** [comment]
@krdln,

re-assigned the units ticket back to you

**Comment by krdln** [comment]
To clarify my understanding – regarding _signals_ (`incoming_concurrency` / `accepted_concurrency`) there's no rename per se, but just a change of units – right?

**Comment by krdln** [comment]
> Concurrency metrics need to be renamed to reflect that they are measuring work done in units of time

@tanveergill Should do rename also the `tokens` concept in configuration to `work` or so? (eg. `Workload.work_seconds`, `Scheduler.auto_work_size` or something like that). Otherwise, there's inconsistency that one configures `tokens`, but in metrics they appear as `work`

**Comment by tanveergill** [comment]
@krdln 
Current terms are auto_tokens and tokens

auto_work doesn't really sound like a mechanism to estimate the size of work.

Maybe auto_sizing and work_seconds. Or auto_work_tokens and work_token_seconds

cc: @harjotgill

**Comment by harjotgill** [comment]
auto_estimate_size?
auto_estimate_cost?

**Comment by tanveergill** [comment]
> To clarify my understanding – regarding _signals_ (`incoming_concurrency` & `accepted_concurrency`) there's no rename per se, but just a change of units – right?

@krdln
incoming_concurrency and accepted_concurrency should be renamed to reflect what they are measuring. We get concurrency (unitless) only when a rate query is performed

@harjotgill 
In case of manual token overrides the tokens can mean anything, right? So maybe we can rename it to something like incoming_work. The default work unit is seconds

**Comment by krdln** [comment]
This is done. Will open separate feature to address just the tokens.
