### ISSUE TITLE
Migrate rate limit tutorials to use blueprint

### ISSUE THREAD

**Issue by harjotgill** [fluxninja/aperture#1297]
A couple of tutorials use raw policies instead of using blueprints.
Please migrate these to use static rate limiting blueprint --
1. https://docs.fluxninja.com/development/tutorials/integrations/flow-control/rate-limiting/static-rate-limiting
2. https://docs.fluxninja.com/development/tutorials/integrations/flow-control/classification/graphql-rate-limiting

Please look at recent updates to Concurrency Limits tutorial to see how we show the values.yaml and jsonnet mixin tabs as well as the final policy that is generated.

Bonus -- Please see if we can add rate limiting dashboard screenshot if it is not too much work. Can skip this if there are other important items.

**Comment by slayer321** [comment]
https://github.com/fluxninja/aperture/pull/1303, https://github.com/fluxninja/aperture/pull/1339 .. this 2 PR closes the issue
