### ISSUE TITLE
Create composite component from `LoadActuator` and `Alerter`

### ISSUE THREAD

**Issue by kwapik** [fluxninja/aperture#1306]
In the current implementation, we have Alerter "hardcoded" into the `LoadActuator` component. Instead of that we should have a composite component with `LoadActuator` and `Alerter` nested components.

The functionality should be exactly the same as current, with one exception - there should be `service` label propagated which is added to the alerter with use of custom labels config. The value of the label is the name of the service.

**Comment by tanveergill** [comment]
@kwapik, @DariaKunoichi,

This functionality can be part of the existing AIMDConcurrencyController component
