### ISSUE TITLE
Remove GetAgentGroup from FluxMeter, Limiter etc. in Dataplane since it is pre-determined by the Agent

### ISSUE THREAD

**Issue by tanveergill** [fluxninja/aperture#136]
**Describe the solution you'd like**
* Eliminate `GetAgentGroup` function from Limiter and FluxMeter interfaces and implementations
* Wherever required, get the AgentGroup from `agentinfo.AgentInfo` instead

**Comment by DariaKunoichi** [comment]
Seems to be already done.
