### ISSUE TITLE
Migrate Otel contrib packages to separate plugins

### ISSUE THREAD

**Issue by harjotgill** [fluxninja/aperture#1455]
Currently we add all otel contrib packages and start them whether the user intends to use them or not. We should move these packages into separate plugins at the agent level (instead of service) i.e. under `plugins/agent` directory. 

We should also group them and enable them based on what they work with, e.g. all AWS contrib packages can be under `plugins/agent/otel-aws` and all k8s plugins can be under `plugins/agent/otel-k8s`.

**Comment by krdln** [comment]
This will be solved as part of #1510

**Comment by hasit** [comment]
This is done in b57dcf11ebef6c6908735ec05fbc0deadc2c725d
