### ISSUE TITLE
Per-agent-group otel collector custom metrics

### ISSUE THREAD

**Issue by krdln** [fluxninja/aperture#1628]
**Is your feature request related to a problem? Please describe.**
Currently, custom metric configuration is the same for all agents, which is not always desirable. Eg. applying [rabbitmq example](https://docs.fluxninja.com/reference/configuration/agent#agent-o-t-e-l-config) yields duplicated metrics, which is bad for two reasons:
* makes a mess in prometheus,
* introduces unnecessary load on api which exposes metrics.

**Describe the solution you'd like**
Ability to mark custom metric receiver as "per-agent-group" singleton.

Implementation-wise, we can use agent leader to perform the collection. Underlying receiver can be wrapped in a wrapper, which would dynamically enable the receiver only when agent becomes a leader.

**Describe alternatives you've considered**
* Use Otel collector dynamic config (#1510) and load new receivers on otel restart. Collector hot restart has some problems, and the mechanism seems a bit overkill for this feature.
* Always enable the receiver, then filter out metrics on non-leaders. This is simple to implement, but also very wasteful.
* Use additional "per-cluster" agent which would collect cluster-wide metrics. We don't want to have "another entity", especially if we already have leader election.
* (This addresses rabbitmq only) Instead of rabbitmq receiver in collector, use rabbitmq_prometheus plugin on rabbitmq and prometheus receiver in collector (where we can perhaps handle node-locality in some different way). Haven't investigated this solution too much as it's not obvious if it works, requires changing configuration of rabbitmq and also is rabbitmq-specific, and we're surely want some generic solution.

**Additional context**
After implementing this, we can properly document how to implement rabbitmq metrics integration – using this feature.

cc @kwapik

**Comment by tanveergill** [comment]
@krdln,

IMO, it's okay to ask users to install dedicated cluster wide Agent Deployment to collect singleton metrics as it significantly simplifies reduces the number of moving parts. cc: @harjotgill

**Comment by krdln** [comment]
@tanveergill I'd agree with you that this would be a better solution _if an alternative would introduce too much complexity in agent_. But the way I'm implementing it right now with "disablable receiver" and piggy backing on already-existing leader-election is simple enough that separate deployment is IMO unnecessarily complex
