### ISSUE TITLE
Kubernetes specific frontend for AutoScaler

### ISSUE THREAD

**Issue by tanveergill** [fluxninja/aperture#1646]
## Why
* AutoScaler is a generic component that can be used for auto-scaling any type of infrastructure.
* It uses generic terms for concepts representing underlying resources and refrains from using terms like replicas.
* Although powerful, it can be confusing and unfriendly for users. 
* Therefore, we need a Kubernetes specific frontend for AutoScaler that will simply translate the spec to the underlying AutoScaler spec internally.

## What
* A `PodAutoScaler` component
* Instead of `max_scale`, `min_scale`, say `max_replicas` and `min_replicas`
* Instead of `actual_scale`, `configured_scale`, `desired_scale`, say `actual_replicas`, `configured_replicas`, `desired_replicas`
* Instead of `scaler`, `pod_scaler` of type `AutoScaler.KubernetesReplicas`

## How
* Rewrite the `PodAutoScaler` spec to `AutoScaler`
* Call `autoscale.ParseAutoScaler` to get a `NestedCircuit` in factory. Update the call signature to take component name so that the `NestedCircuit` component can be updated for visualization purposes

**Comment by tanveergill** [comment]
@hdkshingala,

Please use your description to determine whether we need a Kubernetes specific frontend for `AutoScaler` or directly implement a Kubernetes friendly API in the blueprint only.

**Comment by hdkshingala** [comment]
@tanveergill So If I understand this correctly, we want to have a third option in `AutoScale.Component` (which has `pod_scaler` and `auto-scaler`) named `pod_auto_scaler` with same fields as `auto_scaler` but with renames as you suggested and internally, convert it to `auto_scaler` for processing.

Please correct me if I misunderstood something.

Only exposing this in Blueprints might be confusing so it is better to have it as API and then use in Blueprints
