### ISSUE TITLE
Blueprints for auto-scaling

### ISSUE THREAD

**Issue by tanveergill** [fluxninja/aperture#1647]
## What
* Blueprints hierarchy
  * auto-scale/base
    * What:
      * Not a real blueprint but rather shared code for the variants.
      * There is a function that takes a ScalingBackend and generates the policy.
      * The base policy expects the variants to define the ScalingBackend.
    * Policy:
      * Constructs `AutoScaler` component without the Scaler.
      * Config:
        * promql_scale_out_controllers (new schema): List of scale out controllers.
          * Attributes: Query string, threshold, GradientParameters with sensible defaults
          * Constructed as ScaleOutController.IncreasingGradient with signal from PromQL and constant threshold
        * promql_scale_in_controllers: Similar as above but for scale in.
        * scaling_parameters (refers to ScalingParameters schema in policy proto)
  * auto-scale/pod-auto-scaler
    * What:
      * Builds upon base. Invokes the policy function with KubernetesReplicas scaling backend
      * Config:
        * Inherits base config plus below
        * kubernetes_replicas (refers to KubernetesReplicas schema in policy protocol)

**Comment by hdkshingala** [comment]
@tanveergill Could you please help me with the panels we want to add in the Grafana dashboard for this blueprint?

**Comment by tanveergill** [comment]
> @tanveergill Could you please help me with the panels we want to add in the Grafana dashboard for this blueprint?

We can plot the signals `ACTUAL_SCALE`, `CONFIGURED_SCALE`,`DESIRED_SCALE`

**Comment by tanveergill** [comment]
@hdkshingala,

It's okay to do the dashboard libsonnet. But you can hold off on the policy blueprint as I am thinking about `oneof` Circuit recipes defined in the proto itself instead of designing in libsonnet since that will be more modular and extensible. Blueprint are usually just a shim around these recipes with the required and important values highlighted for the user or important/popular use-cases pre-filled

**Comment by tanveergill** [comment]
> @tanveergill I have added blueprints structure and policy.libsonnet in #1682 so let me know if we just want to merge PodAutoScaler. I'll drop the blueprints commit there for now

It's okay to retain the policy blueprint if you already have it

**Comment by hdkshingala** [comment]
Okay cool.. I'll add the missing dashboards panels in it and that PR will be ready to merge

**Comment by tanveergill** [comment]
@hdkshingala,
Re-opened this for re-introducing auto scale blueprints based on schema based design. Needs some changes to auto scaler spec in my private branch which I'll be pushing over the weekend
