### ISSUE TITLE
Documentation of some fields in agent config is not visible

### ISSUE THREAD

**Issue by krdln** [fluxninja/aperture#1685]
**Describe the bug**
Documentation of some fields in agent config seems missing from rendered docs, despite being present in the code

**Steps to reproduce**
Compare rendered docs (eg. [otel config](https://docs.fluxninja.com/development/reference/configuration/agent#agent-o-t-e-l-config) or [custom metrics config](https://docs.fluxninja.com/development/reference/configuration/agent#custom-metrics-config)) with their [code](https://github.com/fluxninja/aperture/blob/71e37f953fd9ef679d8b4c4a94dcd10b35cba41a/cmd/aperture-agent/config/types.go#L53-L65) [counterparts](https://github.com/fluxninja/aperture/blob/71e37f953fd9ef679d8b4c4a94dcd10b35cba41a/cmd/aperture-agent/config/types.go#L107-L131)

**What did you expect to see?**
Comments for all fields

**What did you see instead?**
Only first field seems to be documented

---

This leaves bad impression for custom metrics config, which is fairly well documented, but rendered docs lacks the comments.

**Comment by harjotgill** [comment]
Looks like this broke recently

**Comment by hdkshingala** [comment]
Yes @harjotgill, we need to add a new line between comment and kubebuilder annotation to fix this.
I'll raise a PR with changes.

**Comment by hdkshingala** [comment]
It looks like whenever the field type is a struct, comment is not added in generated doc. 
It is added for all native field types.

**Comment by hdkshingala** [comment]
I checked a bit more on this and seems like when `$ref` is present, swagger doesn't load anyother fields and that's why we are not seeing documentation when field type is model struct.

Somewhat similar issue raised on Swagger UI - https://github.com/swagger-api/swagger-ui/issues/4829
