### ISSUE TITLE
Improve buttons we use within Tilt 

### ISSUE THREAD

**Issue by kklimonda-fn** [fluxninja/aperture#188]
Add some extra buttons to make tilt interactions more enjoyable:

- Button to stop the traffic (as it is running the scenario continuously by default).
- Button to start the traffic.
- Button to remove the default policy (as it's loaded by default).
- Button to add the default policy.
- Button to open Grafana UI -- also see if we can open it by default when we open Tilt UI.
- Buttons to add/remove a classification rule (though default policy is working on headers).

**Comment by harjotgill** [comment]
Obsolote in favor of #468
