### ISSUE TITLE
Remove mention of batching processor from custom metrics docs

### ISSUE THREAD

**Issue by krdln** [fluxninja/aperture#1953]
Docs for custom metrics / infra meters always suggest adding batch processor. ([eg. here](https://docs.fluxninja.com/development/get-started/integrations/metrics/rabbitmq)). This is not necessary and perhaps even harmful. (Note that the pipeline we define is not a full pipeline, we append our processors & exporters anyway).

cc @hdkshingala @hasit

**Comment by hdkshingala** [comment]
We only need change in a single file now as all the other docs are generated from there - https://github.com/fluxninja/aperture/blob/main/docs/tools/otel_collectors/template.md
