### ISSUE TITLE
Some examples from autogenerated markdown files are not valid

### ISSUE THREAD

**Issue by kklimonda-fn** [fluxninja/aperture#202]
Some of the example code from our autogenerated markdown files seem broken:

```
Example:

````yaml
selecto…
* [v1ControlPoint](#v1-control-point) – Identifies control point within a service that the rule or policy should apply t…
```
there is even some embedded HTLM code later in the same code block.

Or this one:

```
Example:

```yaml
Example of Declarative JSON extractor:

```

**Comment by krdln** [comment]
oh, that's caused by table-of-contents logic cutting descriptions in half, on it
