### ISSUE TITLE
Setpoint is always zero in rabbimq scenario

### ISSUE THREAD

**Issue by krdln** [fluxninja/aperture#2052]
**Steps to reproduce**
in playground:
```sh
nice tilt up -- --race --manual --scenario scenarios/rabbitmq-queue-buildup/
```

**What did you expect to see?**
Setpoint equal to what's set in policy – 1000.

**What did you see instead?**
Setpoint (`signal_reading{signal_name="SETPOINT"}`) equal to zero, resulting in very aggressive load schedding.

**What version did you use?**
d9d0bab52e4c1a44ee97efe8dcfcebdd9cdb68b5

**Comment by krdln** [comment]
Looks like we receive DynamicConfigUpdate on the Variable component, on which `!unmarshaller.IsSet(key)` hits (so key is not set). This raises couple of questions:

* is this even supposed to happen?
* if it is – what should we do? Just hold the previuosly set value? Or set the initial constant? :shrug: 

For now, as a quick fix, we'll implement "hold previously set value" and let's think about why and what later.

**Comment by DariaKunoichi** [comment]
@krdln is this issue resolved?

**Comment by krdln** [comment]
This was fixed already in https://github.com/fluxninja/aperture/pull/2054. Created https://github.com/fluxninja/aperture/issues/2385 for tackling followup fixes.
