### ISSUE TITLE
No auth provider for kubernetes in aperturectl

### ISSUE THREAD

**Issue by akevdmeer** [fluxninja/aperture#2331]
We use oidc authentication with Kubernetes. Installing Aperture with aperturectl install failed with the following error:

`ERR aperturectl/cmd/root.go87 > Error executing aperturectl error="failed to create new ClientSet: no Auth Provider found for name \"oidc\"" service=aperturectl`

Adding an import for `"k8s.io/client-go/plugin/pkg/client/auth/oidc"` fixes it in my local build but I'm unsure where it ought to be added (or would PR).

**Comment by kwapik** [comment]
Reference in the example in client-go repo https://github.com/kubernetes/client-go/blob/master/examples/out-of-cluster-client-configuration/main.go#L44-L62

**Comment by hdkshingala** [comment]
Thank you @akevdmeer for reporting the issue.

We have merged a fix for this in main so could you please try that out once and verify the issue has been fixed for you?
