### ISSUE TITLE
Polish cloud controller

### ISSUE THREAD

**Issue by krdln** [fluxninja/aperture#2346]
https://github.com/fluxninja/aperture/issues/2308 implemented basic support for configuring connection to cloud controller, but there are a few things that can be improved:

- [x] #2372
- [x] #2371
- [x] #2368
- [x] #2369
- [x] #2370
- [x] #2373
- [x] #2388
- [x] #2402
- [x] #2420

**Comment by kwapik** [comment]
@krdln @kklimonda-fn can this one be closed?
