### ISSUE TITLE
CLI: aperturectl policy apply should work with both CRD and policy.yaml

### ISSUE THREAD

**Issue by tanveergill** [fluxninja/aperture#2352]

**Comment by hasit** [comment]
This seems unnecessary. `k apply -f` is just as easy and we do not need to provide yet another way to apply a kubenetes resource.

**Comment by hdkshingala** [comment]
@hasit This is needed when the controller is in cloud.

I can take this if @karansohi if busy with other stuff.

**Comment by hdkshingala** [comment]
This is handled in #2374 as I needed it to upload policy onlatest using API to cloud controller.
