### ISSUE TITLE
OTel collector hangs at Starting state

### ISSUE THREAD

**Issue by hdkshingala** [fluxninja/aperture#2356]
While working on #2355, we have observed that if we have 2 policies having same infra_meters, for example, kubeletstats, the agent starts getting 503 errors on readiness probe and eventually dies.

This seems an intermittent issue as it works sometimes also.

To reproduce this, deploy 2 policies having infra_meters or in load-scheduling blueprints, use `kubelet_overload_confirmations` in both the policies and see agent's probes after the policies are applied.

**Comment by hasit** [comment]
I tried running as mentioned in the description and wasn't able to reproduce this. @hdkshingala, perhaps you can show me what you see?

**Comment by hdkshingala** [comment]
I'll share the exact steps.

**Comment by hdkshingala** [comment]
@hasit I have updated the rabbitmq scenario in branch: `GH-2356-reproduction-steps` and I was able to re-produce this on it.

Run below command:
```
tilt up -- --scenario scenarios/rabbitmq-queue-buildup/
```

As this is an intermittent issue, if once all the apps are up in tilt and you don't see the readiness failures on the agent in ~30 seconds, try restarting just the `scenario-policies` tab from the tilt UI.

**Comment by hdkshingala** [comment]
I feel the issue is when we apply multiple policies together, the OTel config hot reload happens multiple times for each policy and somehow the OTel collector is getting stuck somewhere due to that.

It starts working if we restart the agent after getting those readiness probe failures.

**Comment by hdkshingala** [comment]
You'll see below errors under the agent tab on tilt UI:
```
[event: pod aperture-agent/aperture-agent-gct9g] Readiness probe failed: HTTP probe failed with statuscode: 503
[event: pod aperture-agent/aperture-agent-xncns] Readiness probe failed: HTTP probe failed with statuscode: 503
```

And when you hit the `/v1/status/system/readiness` call on one of the agent, you'll see below:
```
{"status":{"message":null,"error":null,"timestamp":null},"groups":{"component:otel-collector":{"status":{"message":{"@type":"type.googleapis.com/google.protobuf.StringValue","value":"Starting"},"error":{"message":"otel-collector is not running. State: Starting"},"timestamp":"2023-07-12T05:36:03.128592269Z"},"groups":{}},"component:platform":{"status":{"message":{"@type":"type.googleapis.com/google.protobuf.StringValue","value":"platform running"},"error":null,"timestamp":"2023-07-12T05:31:14.262192416Z"},"groups":{}}}}
```
