### ISSUE TITLE
make aperture sdk not block readiness on connecting to agent (breaking "dogfooding recursion deadlock")

### ISSUE THREAD

**Issue by kklimonda-fn** [fluxninja/aperture#2371]

**Comment by IridiumOxide** [comment]
After setting:

- in aperture-agent
    - fluxninja.enable_cloud_controller: true
- in agent-service:
    - aperture_sdk.enabled: true

and running `tilt up agent agent-service`, the agent, agent-service, and cloud controlled etcd all become ready - the bug is currently not reproducible.
