### ISSUE TITLE
Handle etcd connectivity issues gracefully ("etcd robustness")

### ISSUE THREAD

**Issue by krdln** [fluxninja/aperture#2464]
Currently, agent enters a crash-loop when it looses etcd connectivity for more than one minute (the default lease ttl). This is undesirable, as it could happen when eg. agent temporarily loses connectivity to the FluxNinja Cloud Controller. We should handle it in a more graceful way – agent can continue executing currently existing policies and sending telemetry.

Agents being in crash loop turns all the integrations into fail-open state, but this fail-open has a latency overhead – integrations still try to connect to Agent and it's the connection timing out that causes fail-open behaviour.

## Tentative implementation plan

I plan to implement it in steps, so that we can start having some value with minimal effort:

On losing etcd connectivity:
1. Let it crash and restart in "waiting for etcd" state (telemetry will be sent, fail-open will be quick).
2. Unload all components and "soft-restart" into "waiting for etcd" state.
3. Don't unload anything, let the components operate with last-known state, reload components at reconnect.
   > [!NOTE]
   > While the default behaviour for components will be to operate with last-known state, a particular component can implement its own logic on what to do. Eg. a load-shedder may want to switch to "internal fail-open" state to avoid load-shedding basing on stale load shed factor.
4. Don't unload anything, let the components operate with last-known state, **reconcile** components at reconnect. Reconcile instead of reload so that eg. load-scheduler won't loose it's queue state if its configuration haven't actually changed.

TODO: paste the notes about etcd robustnes

**Comment by tanveergill** [comment]
Done
