### ISSUE TITLE
Add logging sampler

### ISSUE THREAD

**Issue by kwapik** [fluxninja/aperture#261]
To prevent log flood, like one fixed in https://github.com/fluxninja/aperture/pull/260, some log sampling needs to be introduced.

`BurstSampler` should be introduced to the platform logger, with appropriate config. See https://pkg.go.dev/github.com/rs/zerolog#section-readme

**Comment by seunghyupoh3517** [comment]
We already have sampled logger functions in the platform logger and can customize the `sampler` for the log samplings.
