### ISSUE TITLE
Add agent_group label through OTEL pipeline so that it applies to all metrics

### ISSUE THREAD

**Issue by tanveergill** [fluxninja/aperture#3085]

**Comment by hdkshingala** [comment]
@tanveergill Seems like we already add a processor to insert the agent_group attributes in logs and metrics - https://github.com/fluxninja/aperture/blob/main/cmd/aperture-agent/agent/provider.go#L30

Please let me know the metrics not having the agent_group label and I can check which pipeline is handling it

**Comment by tanveergill** [comment]
@hdkshingala,

Just picked up a random metric. Did not see `agent_group` label on it. Also, noticed that we have been injecting these label manually on some metrics: https://github.com/fluxninja/aperture/blob/main/pkg/policies/flowcontrol/service/check/metrics.go#L81
<img width="984" alt="Screenshot 2024-01-05 at 6 33 35 PM" src="https://github.com/fluxninja/aperture/assets/3925292/90c684d5-d034-48d5-9e30-36aba5961b38">
