### ISSUE TITLE
Eliminate code repetition in OTEL components

### ISSUE THREAD

**Issue by tanveergill** [fluxninja/aperture#350]
**Describe the solution you'd like**
* Eliminate code repetition at following
  * Across log and trace processing in metrics processor and rollup processor
  * Across log, trace and metric iteration in `otelcollector.Iterate*`
  * Across switch cases in `otelcollector.IterateDataPoints`
* Use go generics or act on common structs so that the same function can operate on `ptrace.Traces`, `plog.Logs` or `pmetric.Metric` (Mostly addressed since Span has been removed from the pipelines)

**Comment by DariaKunoichi** [comment]
Obsolete
