### ISSUE TITLE
`DURATION` field is not filtered out

### ISSUE THREAD

**Issue by kwapik** [fluxninja/aperture#423]
`DURATION` field i.e. [`EnvoyDurationLabel`](https://github.com/fluxninja/aperture/blob/main/pkg/otelcollector/consts.go#L77) is not filtered out. This results is high cardinality on the output.

**Comment by kwapik** [comment]
@tanveergill please take a look and confirm this is an issue.

**Comment by kwapik** [comment]
I believe it is missing in [this list](https://github.com/fluxninja/aperture/blob/9b3cabe6118ea542b2a08fac8044ba565bb82a20/pkg/otelcollector/metricsprocessor/processor.go#L330).

**Comment by tanveergill** [comment]
This is not an issue and expected to be missing for requests dropped by Aperture
