### ISSUE TITLE
Change latency buckets configuration

### ISSUE THREAD

**Issue by kwapik** [fluxninja/aperture#452]
Currently, in [HTTP Server config](https://github.com/fluxninja/aperture/blob/c419c8b15effa115180739a6ce89090ef6b0cd21/pkg/net/http/server.go#L50) we have the following options to configure buckets in latency histogram metric:
```
latency_bucket_start_ms
latency_bucket_width_ms
latency_bucket_count
```
This is not very useful from user's point of view as usually required buckets need to have log or exp scale.

Prometheus client library provides helpers:
https://pkg.go.dev/github.com/prometheus/client_golang@v1.13.0/prometheus#ExponentialBuckets
https://pkg.go.dev/github.com/prometheus/client_golang@v1.13.0/prometheus#ExponentialBucketsRange

But they result in non-integer buckets, which is also not perfect.

The goal of this ticket is to change current way of configuring buckets to a predefined list of buckets, i.e.
```
LatencyBucketsMS []float64 `json:"latency_buckets_ms" validate:"gte=0" default:"[10, 25, 100, 250, 1000]"`
```

**Comment by tanveergill** [comment]
See similar config for FluxMeter buckets in recent PR https://github.com/fluxninja/aperture/pull/473

**Comment by kwapik** [comment]
@tanveergill I've seen it, but decided that we don't need so many options in this case and the code from the other PR was not easily reusable.
