### ISSUE TITLE
Create metrics for RateLimiter and Classifier

### ISSUE THREAD

**Issue by tanveergill** [fluxninja/aperture#459]
**Describe the solution you'd like**
* Need counts for how many times individual RateLimiters (update RateLimiter metrics [here](https://github.com/fluxninja/aperture/blob/43fa9f6a5129a3f9eecb329b943344576027e88d/pkg/otelcollector/metricsprocessor/processor.go#L267)) and Classifier (Can iterate over `checkResponse.Classifiers` in `metricsProcessor.updateMetrics` to update Classifier metrics) hit
* Create dashboard for RateLimiter blueprint with throughput panel

**Comment by DariaKunoichi** [comment]
@tanveergill I am conflicted about where is the best place to track classifier related metrics' lifecycle. There are a few possibilities:

1. Hold metric vector in `classification engine `and access individual counters via "normal" engine API (have to add registering/unregistering classifiers to engine API)
2. Hold metric vector in `classification engine` and pass the pointer to it to metricsprocessor.

**Comment by tanveergill** [comment]
@DariaKunoichi,
I have pushed interfaces for [ClassificationEngine and Classifier](https://github.com/fluxninja/aperture/pull/689). ClassificationEngine is the interface for Registering and retrieving Classifiers. You would need to create an implementation for Classifier which would hold the counter metric. Register/Unregister the Classifier with ClassifierEngine [Classifier Mini App Lifecycle](https://github.com/fluxninja/aperture/blob/tgill/classification-interfaces/pkg/policies/dataplane/resources/classifier/provide.go#L110)

OTEL pipeline can lookup the Classifier (which contains the Counter) via ClassifierEngine interface. Make ClassifierEngine interface available as a singleton via Fx just like Engine. Store pointer to ClassifierEngine in `MetricsProcessor.cfg`
