### ISSUE TITLE
Olric metrics

### ISSUE THREAD

**Issue by tanveergill** [fluxninja/aperture#460]
**Describe the solution you'd like**
* Periodically scrape metrics from [DMaps struct](https://pkg.go.dev/github.com/buraksezer/olric@v0.4.7/stats#DMaps) and publish to prom metrics

**Comment by seunghyupoh3517** [comment]
@tanveergill From olric instance in `Distcache`, `olric.Stats()` returns Stats that exposes statistics about the current state of the member which contains `DMaps`, global DMap statistics. We can scrape metrics from `DMaps` and set gauge metrics value accordingly after olric starts - I believe the best place to track the `DMaps` struct is where we initiate olric and provide `Distcache`, I wonder what you think.

**Comment by tanveergill** [comment]
@seunghyupoh3517,
The high level description sounds good to me, cc: @harjotgill

**Comment by seunghyupoh3517** [comment]
- Data race in Olric repo is fixed - https://github.com/fluxninja/aperture/issues/761
- Re-adding the features back needed
