### ISSUE TITLE
High level APIs for defining histogram buckets of FluxMeter

### ISSUE THREAD

**Issue by tanveergill** [fluxninja/aperture#469]
**Describe the solution you'd like**
* Change `histogram_buckets` to a oneof field
* Following possible values for `histogram_buckets`:
  * repeated double buckets
  * `LinearBuckets linear_buckets`: Fields similar to args of [prometheus.LinearBuckets](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#LinearBuckets))
  * `ExponentialBuckets exponential_buckets`: Fields similar to args of [prometheus.ExponentialBuckets](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#ExponentialBuckets)
  * `ExponentialBucketsRange exponential_buckets_range`: Fields similar to args of [prometheus.ExponentialBucketsRange](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#ExponentialBucketsRange)
* Keep current default value i.e. `buckets = [5.0,10.0,25.0,50.0,100.0,250.0,500.0,1000.0,2500.0,5000.0,10000.0]`

**Comment by seunghyupoh3517** [comment]
`oneof` field cannot have `repeated` fields - [ref](https://developers.google.com/protocol-buffers/docs/proto3)

**Comment by seunghyupoh3517** [comment]
I can create another message type for the double buckets which has repeated double in order to make this work

**Comment by tanveergill** [comment]
@seunghyupoh3517, sounds good
