### ISSUE TITLE
Investigate telemetry issues with Istio 1.15.0

### ISSUE THREAD

**Issue by harjotgill** [fluxninja/aperture#483]
**Describe the bug**
No telemetry observed when using Istio 1.15.0

**Steps to reproduce**
Update chartfile to use Istio 1.15.0

**Desired Outcome**
1. Fix issue with our config in case it's incompatible with latest Istio/Envoy
2. Open a ticket for Istio/Envoy if the telemetry (otel access logging) is broken in their latest release.

**Comment by harjotgill** [comment]
could be related - https://github.com/envoyproxy/envoy/issues/23021

**Comment by krdln** [comment]
Seems to be caused by this https://github.com/envoyproxy/envoy/issues/23234 – istio 1.15.0 uses envoy 1.23.1, while istio 1.14.3 uses envoy 1.22.3.

A quick workaround for us could be a downgrade of otel collector to 0.57.2.

**Comment by harjotgill** [comment]
Closing this ticket here.
