### ISSUE TITLE
EnvoyFilter ext authz breaks when using GRPC streaming APIs

### ISSUE THREAD

**Issue by harjotgill** [fluxninja/aperture#485]
**Describe the bug**
External Authz breaks when using GRPC streaming while `request_body` is enabled. 

**Desired Outcomes**
1. Find out if it's possible to ignore streaming connections using match rules
2. If not, document how we can exclude such traffic (based on destination IP ranges and ports) using Istio's exclude rules.

**Comment by krdln** [comment]
Closing to avoid duplicated issues.
