### ISSUE TITLE
Speed up ConfigMap sync in playground (Kind)

### ISSUE THREAD

**Issue by harjotgill** [fluxninja/aperture#487]
**Is your feature request related to a problem? Please describe.**
https://kubernetes.io/docs/concepts/configuration/configmap/#mounted-configmaps-are-updated-automatically

**Comment by hdkshingala** [comment]
When we will have the CRD for policy, this issue will be resolved as we will be having a watcher for Policy custom resources and they'll pick the events in real time.

I ran a test using the existing file watcher from Controller and the Policy was added and removed as soon as did operations using `kubectl`.
