### ISSUE TITLE
Rollup based on source and metrics

### ISSUE THREAD

**Issue by tanveergill** [fluxninja/aperture#515]
**Current implementation**
* Generic rollups for all sources and metric types

**Describe the solution you'd like**
1. ~~Rollups based on source: Request and Response length only for Envoy source~~
2. Rollups based on type of metric: Create data sketch rollups only in case of Duration type metrics

**Additional context**
* ~~Refer how metrics processor is processing based on source of metrics~~

**Comment by krdln** [comment]
@tanveergill 
> Rollups based on source: Request and Response length only for Envoy source

I think this introduces only additional complexity. We should simply skip rollup if field doesn't exist. Which  _is_ already the current logic).

**Comment by krdln** [comment]
Reopening, as this is still valid point
> 2. Rollups based on type of metric: Create data sketch rollups only in case of Duration type metrics
