### ISSUE TITLE
Cardinality limits per attribute before aggregation rollup 

### ISSUE THREAD

**Issue by tanveergill** [fluxninja/aperture#535]
**Describe the solution you'd like**
* The Rollup processor calculates aggregates on a batch of Logs 
* For every batch, maintain a count of unique attribute values per attribute key. Discard the counts after the batch is aggregated.
* Once the count increases beyond the ATTRIBUTE_CARDINALITY_LIMIT (default of 250) replace any new attribute values from that point with the string: `REDACTED_VIA_CARDINALITY_LIMIT`

**Additional context**
* Need this protection in order to cap the dimension resolution of OLAP telemetry.
* This would ensure that a high cardinality field does not overwhelm an OLAP backend while providing a size-able sample of actual attribute values.

**Comment by krdln** [comment]
@tanveergill Do you think it'd be enough? If it's computed per-batch, _per-agent_, then in sidecar deployments with lots of pods, you could still end up with 10k unique values per second.

> ATTRIBUTE_CARDINALITY_LIMIT

I guess it should be configurable in agents.fluxninja.com object?

**Comment by krdln** [comment]
Pausing work on this to fix https://github.com/fluxninja/aperture/issues/671 and https://github.com/fluxninja/aperture/issues/686 first.

**Comment by tanveergill** [comment]
@krdln,
It should be enough for now. Better than unbounded per batch right now.
