### ISSUE TITLE
Erroneous aperture help prompt

### ISSUE THREAD

**Issue by IridiumOxide** [fluxninja/aperture#541]
**Describe the bug**
When running aperture using `go run` command we can observe irregularities:

- commandline argument parser seems to be instantiated twice with differend cli arguments
- sometimes (when testing on a VM, in service mode)  the agent fails before the logger is up, thus leaving no readable logs

**Steps to reproduce**
`go run ./cmd/aperture-agent --help`

**What did you expect to see?**
```
Usage of aperture-agent:
      --config_path string   path to configuration file (default "/etc/aperture/aperture-agent/config")
      --dot_file string      create fx dot file
```

**What did you see instead?**
```
Usage of aperture-agent:
      --config_path string   path to configuration file (default "/etc/aperture/aperture-agent/config")
Usage of aperture-agent:
      --config_path string   path to configuration file (default "/etc/aperture/aperture-agent/config")
      --dot_file string      create fx dot file
```

**What version did you use?**
Version: f924a752d6219748f88bc2b1bfebeeb60cda20db

**What config did you use?**
Config: the one that's generated inside tilt cluster

**Comment by harjotgill** [comment]
This is the normal behavior as I initiate 2 Fx apps -- a throw-away app is created to read the plugin config and create registry and then the main map. Check platform.go.

**Comment by IridiumOxide** [comment]
As this is normal behavior, I'm closing this issue and will create another one for the logless aperture failure
