### ISSUE TITLE
Add example policy for SDK

### ISSUE THREAD

**Issue by kwapik** [fluxninja/aperture#667]
For now, we only have example policy for envoy based setup. We need one for SDK.

Check example applications for proper selectors
* [Go SDK](https://github.com/fluxninja/aperture-go/blob/main/example/main.go)
* [Java SDK](https://github.com/fluxninja/aperture-java/blob/main/src/main/java/com/fluxninja/aperture/example/App.java)

**Comment by harjotgill** [comment]
This is done, I believe.
