### ISSUE TITLE
Metrics snapshot for components & signals

### ISSUE THREAD

**Issue by DariaKunoichi** [fluxninja/aperture#687]
**Describe the solution you'd like**
While zooming in policy circuit should show metrics. Each signal and component like actuators should show relevant last heartbeat - raw metrict e.g. loadshed. These metrics should be consisted with lastly updated snapshot (not aggregates but distinct measurement).

We need backend support to retrieve last updated metric snapshot for policy circuit signals and components.

**Comment by tanveergill** [comment]
@DariaKunoichi,

Need to publish signal values as a protobuf Status object in [`Circuit.Execute`](https://github.com/fluxninja/aperture/blob/main/pkg/policies/controlplane/runtime/circuit.go#L224)
