### ISSUE TITLE
Warn on incompatible k8s version

### ISSUE THREAD

**Issue by krdln** [fluxninja/aperture#883]
### Is your feature request related to a problem? Please describe.
Supported k8s versions are clearly documented, but it's easy to accidently deploy on old version and the failure mode is hard to debug (see #800).

### Describe the solution you'd like
In-your-face warning about using old version of k8s. Not sure what's the most appropriate place would be. My suggestions:
* warn on agent startup,
* warn on helm deployment,
* UI?

**Comment by chiukapoor** [comment]
Hello @krdln, For the `warn on agent startup` I am working on creating an event to be generated by the Agent and Controller if in case the minimum Kubernetes version is not satisfied.

To grab the current Kubernetes version will be following the same method as `kubectl`

https://github.com/kubernetes/kubectl/blob/393c40f5c4acbe48edbc70f8c8696bb623744b76/pkg/cmd/version/version.go#L139

**Comment by chiukapoor** [comment]
Agent aperture control manager log:

```
1.6685863398395433e+09	DEBUG	events	Kubernetes version v1.25.0 is not supported. Please use a kubernetes cluster with version v1.27.0 or above	{"type": "Warning", "object": {"kind":"Agent","namespace":"aperture-agent","name":"agent","uid":"ffe0db7d-fcf5-4685-84b2-da04ae7534f6","apiVersion":"fluxninja.com/v1alpha1","resourceVersion":"14668896"}, "reason": "MinimumKubernetesVersionFail"}
```

controller-aperture-contoller-manager

```
1.6685863398325784e+09	DEBUG	events	Kubernetes version v1.25.0 is not supported. Please use a kubernetes cluster with version v1.27.0 or above	{"type": "Warning", "object": {"kind":"Controller","namespace":"aperture-controller","name":"controller","uid":"26df4d5c-56af-453e-be98-68a1e1ecf63b","apiVersion":"fluxninja.com/v1alpha1","resourceVersion":"14668895"}, "reason": "MinimumKubernetesVersionFail"}
```
