### ISSUE TITLE
Add Armeria server example to the playground

### ISSUE THREAD

**Issue by krdln** [fluxninja/aperture#891]
**Is your feature request related to a problem? Please describe.**
Right now tinkering with armeria integration requires manual deployment or running server locally with `kubectl port forward` (along with pre-defining a service). This adds friction to experimenting with armeria integration, especially to those doing it for the first time.

**Describe the solution you'd like**
Component on playground, with a button to trigger, similarly to how App.java is exposed as java sdk example. The component might be off by default.

cc @kwapik, @IridiumOxide

**Comment by krdln** [comment]
Looks like @hasit already changed the main class from App to ArmeriaServer in https://github.com/fluxninja/aperture/pull/797/files. Clicking on the button makes the curl to decorated endpoint, but log exporting fails, probably due to misconfigured agent address:

```
[armeria-common-worker-epoll-2-1] INFO com.linecorp.armeria.internal.common.JavaVersionSpecific - Using the APIs optimized for: Java 12+
Nov 09, 2022 12:32:17 PM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
SEVERE: Failed to export spans. Server is UNAVAILABLE. Make sure your collector is running and reachable from this network. Full error message:io exception
Running cmd: sh -c "\n# get k8s pod name from tilt resource name\nPOD_NAME=\"$(tilt get kubernetesdiscovery \"aperture-java-example\" -ojsonpath='{.status.pods[0].name}')\"\nkubectl exec -n aperture-java-example \"$POD_NAME\" -- wget http://127.0.0.1:8080/super -O -\n"
Connecting to 127.0.0.1:8080 (127.0.0.1:8080)
writing to stdout
-                    100% |********************************|    13  0:00:00 ETA
written to stdout
Hello, world!
Nov 09, 2022 12:32:24 PM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
SEVERE: Failed to export spans. Server is UNAVAILABLE. Make sure your collector is running and reachable from this network. Full error message:io exception
```

Also, perhaps we want to have both "App" example and "ArmeriaServer" example as buttons?

**Comment by hasit** [comment]
@krdln @slayer321 

Here's what we can do:
1. In `ArmeriaServer` example, add support for reading host and port of Aperture Agent to connect to via environment. See - https://github.com/fluxninja/aperture/blob/main/sdks/aperture-java/src/main/java/com/fluxninja/aperture/example/App.java#L18.
2. Add another Dockerfile for running `App` example. Adding scripts for this would be very helpful. Currently using `gradle run` (which is configured by `application` section in `build.gradle.kts`). Someone with more knowledge on Java build system should do this.

**Comment by slayer321** [comment]
I'm unassigning myself as it requires someone with knowledge on Java build system
