### ISSUE TITLE
Send agent key as label on sentry events

### ISSUE THREAD

**Issue by seunghyupoh3517** [fluxninja/aperture#93]
- Send agent key as a label on sentry events
- Sentry plugin needs to subscribe to agent key from FN Cloud plugin via Fx

- Refactor of Crashwriter included: Keep raw zerolog events in the CrashWriter circular buffer and only do the sentry parsing when panic happens 
(i.e. Convert zerolog to sentry only when it's ready to send those logs to sentry to reduce the unnecessary processing)

**Comment by DariaKunoichi** [comment]
Obsolete
