### ISSUE TITLE
Document how to upgrade the Controller and Agent installations

### ISSUE THREAD

**Issue by tanveergill** [fluxninja/aperture#970]

**Comment by hdkshingala** [comment]
@tanveergill The installation steps are the same for upgrade as well. We use the `helm upgrade -install` so if the resources are not present, they'll get created else they'll get updated.

I'll test a scenario by upgrading aperture from a lower version to higher one and will see if we need any changes in it.

**Comment by tanveergill** [comment]
Would be good to mention that it’s the same step for upgradeOn Nov 24, 2022, at 8:43 PM, hdkshingala ***@***.***> wrote:﻿
@tanveergill The installation steps are the same for upgrade as well. We use the helm upgrade -install so if the resources are not present, they'll get created else they'll get updated.
I'll test a scenario by upgrading aperture from a lower version to higher one and will see if we need any changes in it.
